// ============================================================
// data.js – Hằng số, config, dữ liệu tĩnh
// SDU Life Simulator
// ============================================================

const DATA = {
  WORLD_W: 3840,
  WORLD_H: 2560,
  S: 0.25, // scale: Godot coords × 0.25 = canvas coords
  VIEW_W: 960,
  VIEW_H: 640,
  PLAYER_SPEED: 3,
  PLAYER_SIZE: 14,

  STATS_INIT: {
    energy:100, hunger:80, thirst:80, health:100,
    stress:10, money:2000, gpa:2.5, social:30, skill:10, hygiene:80,
  },

  // decay mỗi giờ game (dương = tăng, âm = giảm)
  DECAY: {
    energy:-2, hunger:-3, thirst:-2.5, stress:+1, social:-0.5, hygiene:-1.5,
  },

  PERIODS: {
    1:{start:7,end:9}, 2:{start:9,end:11},
    3:{start:13,end:15}, 4:{start:15,end:17},
  },

  SCHEDULE: [
    {dow:1,period:1,subject:'Toán cao cấp',room:'nhaA'},
    {dow:1,period:2,subject:'Vật lý ĐC',room:'nhaA'},
    {dow:1,period:3,subject:'TH CNTT',room:'xuong3'},
    {dow:2,period:1,subject:'Lập trình C++',room:'xuong3'},
    {dow:2,period:3,subject:'Kỹ thuật điện',room:'nhaA'},
    {dow:3,period:2,subject:'Toán cao cấp',room:'nhaA'},
    {dow:3,period:4,subject:'TH Cơ khí',room:'xuong2'},
    {dow:4,period:1,subject:'Lập trình C++',room:'xuong3'},
    {dow:4,period:3,subject:'Kỹ thuật điện',room:'nhaA'},
    {dow:5,period:2,subject:'Vật lý ĐC',room:'nhaA'},
    {dow:5,period:3,subject:'TH Ô tô',room:'xuong1'},
  ],

  // Tọa độ đã scale ×0.25 – tính trực tiếp
  BUILDINGS: [
    {id:'nhaA',name:'NHÀ A – Giảng đường',
     x:213,y:195,w:272,h:113,color:'#d97777',zone:'campus',
     actions:['study','exam','present','ask_teacher']},
    {id:'nhaB',name:'NHÀ B – Thư viện & Đào tạo',
     x:25,y:25,w:88,h:175,color:'#d97777',zone:'campus',
     actions:['library_study','library_pc','check_schedule','pay_tuition','view_gpa']},
    {id:'baoVe',name:'Phòng Bảo Vệ',
     x:275,y:25,w:50,h:63,color:'#d97777',zone:'campus',
     actions:['info']},
    {id:'congChinh',name:'CỔNG CHÍNH ↕',
     x:333,y:38,w:70,h:38,color:'#b44444',zone:'campus',
     actions:['view_notice','exit_campus'],isGate:true},
    {id:'nhaDeXe',name:'NHÀ ĐỂ XE',
     x:463,y:63,w:350,h:88,color:'#d97777',zone:'campus',
     actions:['park_bike','get_bike']},
    {id:'cacKhoa',name:'Phòng Các Khoa',
     x:38,y:238,w:125,h:55,color:'#d97777',zone:'campus',
     actions:['meet_advisor','submit_docs']},
    {id:'congPhu1',name:'Cổng Phụ 1',
     x:0,y:275,w:20,h:63,color:'#b44444',zone:'campus',
     actions:['exit_campus'],isGate:true},
    {id:'sanBong',name:'SÂN BÓNG',
     x:545,y:195,w:225,h:200,color:'#5a9e5a',zone:'campus',
     actions:['play_football','join_team','watch_game']},
    {id:'congPhu2',name:'Cổng Phụ 2',
     x:850,y:263,w:25,h:75,color:'#b44444',zone:'campus',
     actions:['exit_campus'],isGate:true},
    {id:'daiPhunNuoc',name:'Đài Phun Nước',
     x:333,y:350,w:43,h:35,color:'#4488cc',zone:'campus',
     actions:['rest','take_photo','meet_friends','listen_music']},
    {id:'xuong1',name:'Xưởng 1 – Ô Tô',
     x:48,y:350,w:80,h:40,color:'#9a7a55',zone:'campus',
     actions:['workshop_practice']},
    {id:'xuong2',name:'Xưởng 2 – Cơ Khí',
     x:48,y:413,w:80,h:40,color:'#9a7a55',zone:'campus',
     actions:['workshop_practice']},
    {id:'xuong3',name:'Xưởng 3 – CNTT',
     x:48,y:475,w:80,h:30,color:'#9a7a55',zone:'campus',
     actions:['workshop_practice','robocon_practice']},
    {id:'xuong4',name:'Xưởng 4 – Robocon',
     x:53,y:525,w:80,h:38,color:'#9a7a55',zone:'campus',
     actions:['robocon_practice','robocon_compete']},
    {id:'hoiTruong',name:'HỘI TRƯỜNG',
     x:245,y:413,w:200,h:70,color:'#7777bb',zone:'campus',
     actions:['watch_event','perform','club_meeting']},
    {id:'theThao',name:'Phòng Thể Thao',
     x:248,y:513,w:200,h:50,color:'#5a9e5a',zone:'campus',
     actions:['exercise','badminton']},
    {id:'ktxA',name:'KÍ TÚC XÁ A',
     x:518,y:413,w:120,h:45,color:'#f5bb44',zone:'campus',
     actions:['sleep','shower','phone','homework','chat_roommate'],isKtx:true},
    {id:'ktxB',name:'KÍ TÚC XÁ B',
     x:670,y:420,w:123,h:45,color:'#f5bb44',zone:'campus',
     actions:['sleep','shower','phone','homework','chat_roommate'],isKtx:true},
    {id:'ktxC',name:'KÍ TÚC XÁ C',
     x:678,y:488,w:115,h:43,color:'#f5bb44',zone:'campus',
     actions:['sleep','shower','phone','homework','chat_roommate'],isKtx:true},
    {id:'cantin',name:'Căng-tin + CTSV',
     x:515,y:488,w:123,h:48,color:'#f5aa44',zone:'campus',
     actions:['buy_food','buy_drink','meet_friends','hear_gossip']},
    // Ngoài trường (outside map – y âm, hiển thị khi ở outside zone)
    {id:'nhaTro',name:'Nhà Trọ',
     x:50,y:50,w:75,h:50,color:'#f5bb44',zone:'outside',
     actions:['sleep','cook','clean_room','study_online'],isKtx:true},
    {id:'quanAn',name:'Quán Ăn',
     x:160,y:50,w:75,h:45,color:'#f5aa44',zone:'outside',
     actions:['eat_restaurant','eat_with_friend']},
    {id:'atm',name:'ATM / Ngân Hàng',
     x:270,y:55,w:50,h:38,color:'#55aaee',zone:'outside',
     actions:['withdraw','check_balance']},
    {id:'quanGame',name:'Quán Game',
     x:350,y:50,w:63,h:40,color:'#aa55ee',zone:'outside',
     actions:['play_game']},
    {id:'nhathuoc',name:'Nhà Thuốc / BV',
     x:445,y:55,w:55,h:38,color:'#ff7777',zone:'outside',
     actions:['buy_medicine','see_doctor']},
    {id:'choMini',name:'Chợ / Siêu thị',
     x:530,y:50,w:63,h:43,color:'#77cc77',zone:'outside',
     actions:['buy_groceries','buy_book','buy_clothes']},
  ],

  ACTIONS: {
    study:          {label:'📚 Đi học',time:2,  eff:{energy:-15,stress:+8,hunger:-10},gpa:0.5},
    exam:           {label:'📝 Thi cử',time:2,  eff:{energy:-20,stress:+20},gpa:2.0,mini:true},
    present:        {label:'🗣️ Thuyết trình',time:1,eff:{energy:-10,stress:+5},skill:5},
    ask_teacher:    {label:'🙋 Hỏi thầy',time:0.5,eff:{energy:-3},gpa:0.1},
    library_study:  {label:'📖 Tự học',time:2,  eff:{energy:-12,stress:+3},gpa:0.3},
    library_pc:     {label:'💻 Dùng máy tính',time:1.5,eff:{energy:-8},gpa:0.2},
    check_schedule: {label:'📅 Xem lịch học',time:0,eff:{}},
    pay_tuition:    {label:'💳 Nộp học phí',time:0.5,eff:{money:-3000}},
    view_gpa:       {label:'🎓 Xem bảng điểm',time:0,eff:{}},
    meet_advisor:   {label:'👨‍🏫 Gặp cố vấn',time:0.5,eff:{stress:-5}},
    submit_docs:    {label:'📄 Nộp giấy tờ',time:0.5,eff:{}},
    workshop_practice:{label:'🔧 Thực hành',time:2,eff:{energy:-15,stress:+5},gpa:0.3,skill:3},
    robocon_practice:{label:'🤖 Luyện Robocon',time:2,eff:{energy:-15,stress:+5},skill:8},
    robocon_compete:{label:'🏆 Thi Robocon',time:3,eff:{energy:-20,stress:+15},skill:20,mini:true},
    homework:       {label:'✏️ Làm bài tập',time:2,eff:{energy:-10,stress:+5},gpa:0.2},
    study_online:   {label:'🌐 Học online',time:2,eff:{energy:-10,stress:+3},gpa:0.25},

    buy_food:       {label:'🍱 Mua cơm (20k)',time:0.5,eff:{hunger:+40,energy:+15,money:-20,thirst:+10}},
    buy_drink:      {label:'💧 Mua nước (5k)',time:0.1,eff:{thirst:+40,money:-5}},
    eat_restaurant: {label:'🍜 Ăn quán (25k)',time:0.5,eff:{hunger:+60,energy:+25,money:-25,thirst:+20}},
    eat_with_friend:{label:'👬 Ăn với bạn',time:1,eff:{hunger:+60,energy:+25,money:-30,social:+10}},
    cook:           {label:'🍳 Nấu ăn',time:1.5,eff:{hunger:+50,energy:+10,money:-10}},
    buy_groceries:  {label:'🛒 Mua đồ ăn',time:0.5,eff:{money:-50}},
    buy_medicine:   {label:'💊 Mua thuốc',time:0.3,eff:{health:+20,money:-30}},
    see_doctor:     {label:'🏥 Khám bệnh',time:2,eff:{health:+60,money:-200}},

    sleep:          {label:'😴 Ngủ (8h)',time:8,eff:{energy:+80,stress:-30,hunger:-20,hygiene:-5}},
    shower:         {label:'🚿 Tắm rửa',time:0.5,eff:{hygiene:+40,stress:-5}},
    phone:          {label:'📱 Lướt điện thoại',time:1,eff:{stress:-10,energy:-5}},
    chat_roommate:  {label:'💬 Nói chuyện bạn phòng',time:0.5,eff:{social:+8,stress:-5}},
    clean_room:     {label:'🧹 Dọn phòng',time:1,eff:{hygiene:+20,stress:-5}},
    rest:           {label:'🌳 Ngồi nghỉ',time:1,eff:{stress:-15,energy:+5}},
    listen_music:   {label:'🎵 Nghe nhạc',time:1,eff:{stress:-12}},
    take_photo:     {label:'📸 Chụp ảnh',time:0.5,eff:{stress:-8,social:+3}},
    meet_friends:   {label:'👥 Gặp bạn bè',time:1,eff:{social:+15,stress:-10}},
    hear_gossip:    {label:'👂 Nghe tin đồn',time:0.3,eff:{social:+5}},

    play_football:  {label:'⚽ Đá bóng',time:1.5,eff:{health:+15,stress:-20,energy:-25,hunger:-15}},
    join_team:      {label:'⚽ Vào đội bóng',time:0.5,eff:{social:+10}},
    watch_game:     {label:'👀 Xem đấu',time:1,eff:{stress:-10,social:+5}},
    exercise:       {label:'🏋️ Tập thể dục',time:1,eff:{health:+10,stress:-15,energy:-15}},
    badminton:      {label:'🏸 Cầu lông',time:1,eff:{health:+8,stress:-12,energy:-12,social:+5}},
    watch_event:    {label:'🎭 Xem sự kiện',time:1.5,eff:{stress:-15,social:+10}},
    perform:        {label:'🎤 Biểu diễn',time:2,eff:{stress:-5,social:+15},skill:8},
    club_meeting:   {label:'📣 Họp CLB',time:1,eff:{social:+10},skill:3},

    withdraw:       {label:'💰 Rút tiền',time:0.2,eff:{money:+500},withdraw:true},
    check_balance:  {label:'💳 Kiểm tra số dư',time:0.1,eff:{}},
    play_game:      {label:'🎮 Chơi game',time:3,eff:{stress:-30,energy:-20,money:-50}},
    buy_book:       {label:'📚 Mua sách',time:0.5,eff:{money:-80}},
    buy_clothes:    {label:'👕 Mua quần áo',time:1,eff:{money:-200}},
    exit_campus:    {label:'🚪 Ra ngoài',time:0,eff:{},exit:true},
    view_notice:    {label:'📢 Xem thông báo',time:0,eff:{},notice:true},
    park_bike:      {label:'🏍️ Gửi xe',time:0.1,eff:{}},
    get_bike:       {label:'🏍️ Lấy xe',time:0.1,eff:{}},
    info:           {label:'ℹ️ Hỏi thông tin',time:0.2,eff:{}},
  },

  RANDOM_EVENTS: [
    {id:'rain',label:'☔ Trời mưa to!',
     msg:'Trời mưa lớn! Bạn cần áo mưa khi ra ngoài.',prob:0.15},
    {id:'blackout',label:'💡 Mất điện KTX!',
     msg:'Mất điện tối nay. Không làm bài hay sạc điện thoại được.',prob:0.08},
    {id:'friend_invite',label:'📱 Bạn rủ đi ăn!',
     msg:'Bạn cùng lớp rủ đi ăn. Đi không?',prob:0.12,
     choices:[
       {label:'Đi thôi! (−30k)',eff:{social:+15,money:-30,hunger:+40}},
       {label:'Thôi lần sau',eff:{}},
     ]},
    {id:'found_money',label:'🎁 Nhặt được tiền!',
     msg:'Bạn nhặt được tiền rơi trên đường!',prob:0.05,
     eff:{money:150}},
    {id:'sick',label:'🤒 Bị cảm cúm!',
     msg:'Bạn bị cảm cúm. Uống thuốc sớm nhé!',prob:0.07,
     condEnergyLt:25,continuous:true},
    {id:'scholarship',label:'🎓 Học bổng!',
     msg:'GPA đủ điều kiện nhận học bổng khuyến học 1.500.000đ!',
     prob:0,eff:{money:1500}},
  ],
};
